name: $name
version: $version
description: $description
author: iAngry, LeoMadrassi
main: me.leodev.trollingfreedomreborn.main.Core
softdepend: [Essentials, Citizens, ProtocolLib]
api-version: $apiVersion
commands:
  trollingfreedom:
    description: Plugin help
    aliases: [ tf ]
  trollgui:
    descrption: Troll GUI open
    aliases: [ltroll,tgui, trollingfreedomgui, tfgui, tfl]
  untroll:
    description: Untroll player
    aliases: [ luntroll, stoptroll ]
  trollf:
    description: Troll with CMD
    aliases: [ trollcmd ]
  unchesttroll:
    description: Stops lock inventory for sender
    aliases: [ unlockinv ]
  panicstoptroll:
    description: stops all troll by this plugin for every player
    aliases: [trollpanic, trollps, pstoptroll, tfrstop, tfstop]
  control:
    description: Lets you control player